#!/usr/bin/env python3
"""Generate roster page TSX — direct bytes, no escaping possible."""
import os

lines = []
lines.append('"use client";')
lines.append('import { useState, useEffect, useCallback } from "react";')
lines.append('import {')
lines.append('  Calendar, Users, Play, Loader2, ChevronLeft, ChevronRight, Plus, X,')
lines.append('  Edit3, Trash2, BarChart3, UserPlus, CalendarPlus, Settings2,')
lines.append('  AlertTriangle, Lock, Unlock, CheckCircle2, RotateCcw, Zap')
lines.append('} from "lucide-react";')
lines.append('import { Button } from "@/components/ui/button";')
lines.append('import { Card, CardHeader, CardTitle } from "@/components/ui/card";')
lines.append('')
lines.append('const DAY_NAMES = ["日","一","二","三","四","五","六"];')
lines.append('const SHIFT_COLORS: Record<string,string> = { "1423":"#22c55e","N":"#6366f1","PA":"#f59e0b","AM":"#14b8a6","PM":"#ec4899","OFF":"#3f3f46" };')
lines.append('')
lines.append('export default function Page() {')
lines.append('  const [staff, setStaff] = useState<any[]>([]);')
lines.append('  const [units, setUnits] = useState<any[]>([]);')
lines.append('  const [roles, setRoles] = useState<any[]>([]);')
lines.append('  const [assignments, setAssignments] = useState<any[]>([]);')
lines.append('  const [monthOffset, setMonthOffset] = useState(0);')
lines.append('  const [dates, setDates] = useState<string[]>([]);')
lines.append('  const [solving, setSolving] = useState(false);')
lines.append('  const [msg, setMsg] = useState("");')

lines.append('')
lines.append('  useEffect(() => {')
lines.append('    const now = new Date();')
lines.append('    const target = new Date(now.getFullYear(), now.getMonth()+monthOffset, 1);')
lines.append('    const days: string[] = [];')
lines.append('    const d = new Date(target);')
lines.append('    while (d.getMonth() === target.getMonth()) { days.push(d.toISOString().slice(0,10)); d.setDate(d.getDate()+1); }')
lines.append('    setDates(days);')
lines.append('  }, [monthOffset]);')

lines.append('')
lines.append('  const loadAll = useCallback(async () => {')
lines.append('    const [sr,su,sl] = await Promise.all([')
lines.append('      fetch("/api/schedule?sub=staff").then(r=>r.json()),')
lines.append('      fetch("/api/schedule?sub=units").then(r=>r.json()),')
lines.append('      fetch("/api/schedule?sub=leave").then(r=>r.json()),')
lines.append('    ]);')
lines.append('    if(Array.isArray(sr)) setStaff(sr);')
lines.append('    if(Array.isArray(su)) setUnits(su);')
lines.append('    if(Array.isArray(sl)) setLeaveList(sl);')
lines.append('  }, []);')

lines.append('  const loadRoster = useCallback(async () => {')
lines.append('    if(dates.length===0) return;')
lines.append('    const r = await fetch("/api/schedule?sub=roster&start="+dates[0]+"&end="+dates[dates.length-1]);')
lines.append('    const d = await r.json();')
lines.append('    if(Array.isArray(d)) setAssignments(d);')
lines.append('  }, [dates]);')

lines.append('  useEffect(() => { loadAll(); }, [loadAll]);')
lines.append('  useEffect(() => { loadRoster(); }, [loadRoster]);')

lines.append('')
lines.append('  const [leaveList, setLeaveList] = useState<any[]>([]);')
lines.append('  const [showStaffForm, setShowStaffForm] = useState(false);')
lines.append('  const [staffForm, setStaffForm] = useState({ name:"",role:"RW",home_unit:"A",can_work_units:"" });')

lines.append('')
lines.append('  function getCell(d:string,u:string) { return assignments.filter((a:any)=>a.shift_date===d&&a.unit===u); }')
lines.append('  function roleColor(code:string) { const r=units.find((x:any)=>x.code===code); return r?r.color:"#666"; }')
lines.append('  function initials(n:string) { return n.slice(0,2); }')
lines.append('  const activeUnits = units.filter((u:any)=>u.is_active!==false);')
lines.append('  const activeStaff = staff.filter((s:any)=>s.is_active!==false);')
lines.append('  const monthLabel = dates.length>0 ? new Date(dates[0]).toLocaleDateString("zh-TW",{year:"numeric",month:"long"}) : "";')

lines.append('')
lines.append('  return (')
lines.append('    <div className="p-4">')
lines.append('      <h1 className="text-xl font-bold text-zinc-100">智能排更 ({activeStaff.length}人)</h1>')
lines.append('      <p className="text-xs text-zinc-500">{monthLabel} · {dates.length}日 · {assignments.length} 更次</p>')
lines.append('      <div className="grid grid-cols-4 gap-3 mt-4">')
lines.append('        <div className="bg-zinc-800/50 rounded-xl p-3"><p className="text-lg font-bold text-zinc-100">{activeStaff.length}</p><p className="text-xs text-zinc-500">職員</p></div>')
lines.append('        <div className="bg-zinc-800/50 rounded-xl p-3"><p className="text-lg font-bold text-zinc-100">{activeUnits.length}</p><p className="text-xs text-zinc-500">家社</p></div>')
lines.append('        <div className="bg-zinc-800/50 rounded-xl p-3"><p className="text-lg font-bold text-zinc-100">{assignments.length}</p><p className="text-xs text-zinc-500">更次</p></div>')
lines.append('        <div className="bg-zinc-800/50 rounded-xl p-3"><p className="text-lg font-bold text-zinc-100">{leaveList.length}</p><p className="text-xs text-zinc-500">請假</p></div>')
lines.append('      </div>')

lines.append('      <div className="flex gap-4 mt-4">')
lines.append('        <div className="w-64">')
lines.append('          <div className="bg-zinc-900/50 rounded-xl p-3 border border-zinc-800">')
lines.append('            <p className="text-xs font-semibold text-zinc-300 mb-2">職員列表</p>')
lines.append('            {activeStaff.map((s:any)=>(<div key={s.id} className="flex items-center gap-2 p-2 rounded-lg bg-zinc-800/50 text-xs mb-1"><div className="w-6 h-6 rounded-full flex items-center justify-center text-[10px] font-bold text-white" style={{backgroundColor:roleColor(s.home_unit)}}>{initials(s.name)}</div><span className="text-zinc-200">{s.name}</span></div>))}')
lines.append('          </div>')
lines.append('        </div>')

lines.append('        <div className="flex-1 overflow-x-auto">')
lines.append('          <div className="bg-zinc-900/50 rounded-xl p-3 border border-zinc-800 min-w-[700px]">')
lines.append('            <div className="flex" style={{marginLeft:"52px"}}>')
lines.append('              {dates.map((date:string)=>{const d=new Date(date);return(<div key={date} className="flex-1 min-w-[85px] text-center py-2"><p className="text-xs text-zinc-400">{d.getMonth()+1}/{d.getDate()}</p><p className="text-[10px] text-zinc-600">{DAY_NAMES[d.getDay()]}</p></div>);})}')
lines.append('            </div>')
lines.append('            {activeUnits.map((unit:any)=>(<div key={unit.code} className="mb-2"><div className="flex items-center gap-2 mb-1"><div className="w-10 h-6 rounded flex items-center justify-center text-[10px] font-bold text-white" style={{backgroundColor:unit.color}}>{unit.code}</div><span className="text-xs text-zinc-400">{unit.name}</span></div><div className="flex" style={{marginLeft:"52px"}}>{dates.map((date:string)=>{const cells=getCell(date,unit.code);return(<div key={date} className="flex-1 min-w-[85px] min-h-[40px] border border-zinc-800/50 rounded p-1 mx-0.5">{cells.map((a:any)=>(<div key={a.id||a.staff_id+"-"+a.shift_date} className="text-[10px] px-1 py-0.5 rounded mb-0.5" style={{backgroundColor:(SHIFT_COLORS[a.shift_code]||"#666")+"20",borderLeft:"2px solid "+(SHIFT_COLORS[a.shift_code]||"#666")}}><span className="text-zinc-200">{a.staff_name}</span><span className="text-zinc-500 ml-1">{a.shift_code}</span></div>))}{cells.length===0&&<div className="text-[10px] text-zinc-700 text-center pt-2">-</div>}</div>);})}</div></div>))}')
lines.append('          </div>')
lines.append('        </div>')
lines.append('      </div>')
lines.append('    </div>')
lines.append('  );')
lines.append('}')

content = '\n'.join(lines)
path = '/home/lemon/lemons-ai-agent/frontend/app/roster/page.tsx'
with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

# Verify no backslash-quote
with open(path, 'rb') as f:
    data = f.read()
count = data.count(b'\\"')
print(f"Wrote {len(content)} chars, {count} escaped quotes (should be 0)")
