"use client";
import { useState, useEffect, useCallback } from "react";
import FullCalendar from "@fullcalendar/react";
import dayGridPlugin from "@fullcalendar/daygrid";
import interactionPlugin from "@fullcalendar/interaction";
import { Loader2, Zap, X, Plus, Edit3, Trash2, UserPlus, CalendarPlus, RotateCcw, Settings2, BarChart3, Lock, Unlock, Download, Copy, Info, SlidersHorizontal, Save } from "lucide-react";
import { Button } from "@/components/ui/button";

const DAY_NAMES=["日","一","二","三","四","五","六"];

export default function Page(){
const[staff,setStaff]=useState([]);const[units,setUnits]=useState([]);const[roles,setRoles]=useState([]);
const[assignments,setAssignments]=useState([]);const[leaveList,setLeaveList]=useState([]);
const[currentMonth,setCurrentMonth]=useState(new Date().toISOString().slice(0,7));
const[solving,setSolving]=useState(false);const[loading,setLoading]=useState(true);const[msg,setMsg]=useState("");
const[showSettings,setShowSettings]=useState(false);const[settingsTab,setSettingsTab]=useState("constraints");
const[showStaffForm,setShowStaffForm]=useState(false);const[editStaffId,setEditStaffId]=useState(null);
const[staffForm,setStaffForm]=useState({name:"",role:"RW",home_unit:"A",can_work_units:""});
const[showLeaveForm,setShowLeaveForm]=useState(false);const[editLeaveId,setEditLeaveId]=useState(null);
const[leaveForm,setLeaveForm]=useState({staff_id:0,start_date:"",end_date:"",leave_type:"annual"});
const[showStats,setShowStats]=useState(false);const[showReplace,setShowReplace]=useState(null);
const loadAll=useCallback(async()=>{try{var[rs,rro,ru,rl]=await Promise.all([fetch("/api/schedule?sub=staff").then(r=>r.json()),fetch("/api/schedule?sub=roles").then(r=>r.json()),fetch("/api/schedule?sub=units").then(r=>r.json()),fetch("/api/schedule?sub=leave").then(r=>r.json())]);if(Array.isArray(rs))setStaff(rs);if(Array.isArray(rro))setRoles(rro);if(Array.isArray(ru))setUnits(ru);if(Array.isArray(rl))setLeaveList(rl);}catch(e){console.error(e)}setLoading(false)},[]);
const loadRoster=useCallback(async()=>{var s=currentMonth+"-01";var d=new Date(s);var e=new Date(d.getFullYear(),d.getMonth()+1,0).toISOString().slice(0,10);var r=await fetch("/api/schedule?sub=roster&start="+s+"&end="+e);var data=await r.json();if(Array.isArray(data))setAssignments(data)},[currentMonth]);
useEffect(function(){loadAll()},[loadAll]);useEffect(function(){loadRoster()},[loadRoster]);
function unitColor(code){var u=units.find(function(x){return x.code===code});return u?u.color:"#666"}
function unitName(code){var u=units.find(function(x){return x.code===code});return u?u.name:code}
function roleColor(code){var r=roles.find(function(x){return x.code===code});return r?r.color:"#666"}
function initials(n){return n.slice(0,2)}
function isOnLeave(sid,d){return leaveList.some(function(l){return l.staff_id===sid&&d>=l.start_date&&d<=l.end_date})}
var activeUnits=units.filter(function(u){return u.is_active!==false});
var activeStaff=staff.filter(function(s){return s.is_active!==false});
var workload=activeStaff.map(function(s){var a=assignments.filter(function(x){return x.staff_id===s.id});return{name:s.name,role:s.role,count:a.length}}).sort(function(a,b){return b.count-a.count});
function getSuggestions(date,unit,excludeSid){var busy=new Set(assignments.filter(function(a){return a.shift_date===date}).map(function(a){return a.staff_id}));var onL=new Set(leaveList.filter(function(l){return date>=l.start_date&&date<=l.end_date}).map(function(l){return l.staff_id}));busy.add(excludeSid);return activeStaff.filter(function(s){if(busy.has(s.id)||onL.has(s.id))return false;return s.home_unit===unit||(s.can_work_units||[]).includes(unit)}).slice(0,5)}
var eventsByUnit={};activeUnits.forEach(function(unit){eventsByUnit[unit.code]=[]});
assignments.forEach(function(a){if(eventsByUnit[a.unit]){var c=a.shift_code==="N"?"#818cf8":a.shift_code==="PA"?"#f59e0b":"#22c55e";eventsByUnit[a.unit].push({title:(a.locked?"LOCK ":"")+a.staff_name+" "+a.shift_code,start:a.shift_date,allDay:true,backgroundColor:c+"CC",borderColor:c,textColor:"#fff",extendedProps:{id:a.id,staff_id:a.staff_id,unit:a.unit,locked:a.locked,staff_name:a.staff_name,shift_code:a.shift_code}})}});
async function handleSolve(){var s=currentMonth+"-01";var d=new Date(s);var e=new Date(d.getFullYear(),d.getMonth()+1,0).toISOString().slice(0,10);setSolving(true);setMsg("");try{var r=await fetch("/api/schedule",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"solve",start_date:s,end_date:e})});var res=await r.json();if(res.error){setMsg(res.error);return}setMsg("OK "+res.status+" - "+res.stats.total_shifts+" shifts");await loadRoster()}catch(ex){setMsg(String(ex))}finally{setSolving(false)}}
async function handleClear(){if(!confirm("Clear all non-locked?"))return;for(var i=0;i<assignments.length;i++){var a=assignments[i];if(!a.locked&&a.id){await fetch("/api/schedule",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"delete",id:a.id})})}}setMsg("");await loadRoster()}
async function handleCopyRoster(){var prevMonth=new Date(currentMonth+"-01");prevMonth.setMonth(prevMonth.getMonth()-1);var fs=prevMonth.toISOString().slice(0,10);var fe=new Date(prevMonth.getFullYear(),prevMonth.getMonth()+1,0).toISOString().slice(0,10);var ts=currentMonth+"-01";await fetch("/api/schedule",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"copy_roster",from_start:fs,from_end:fe,to_start:ts})});await loadRoster()}
function handleExportCSV(){var h="Date,Unit,Staff,Role,Shift\n";var rows=assignments.map(function(a){return a.shift_date+","+a.unit+","+a.staff_name+","+a.role+","+a.shift_code}).join("\n");var blob=new Blob([h+rows],{type:"text/csv;charset=utf-8"});var url=URL.createObjectURL(blob);var a=document.createElement("a");a.href=url;a.download="roster_"+currentMonth+".csv";a.click();URL.revokeObjectURL(url)}
async function handleAssign(sid,date,unit){await fetch("/api/schedule",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"assign",staff_id:sid,date,shift_code:"1423",unit})});await loadRoster();setShowReplace(null)}
async function handleDeleteAss(ep){await fetch("/api/schedule",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"delete",id:ep.id})});setShowReplace({date:ep.shift_date||"",unit:ep.unit,removing:ep.staff_name,staffId:ep.staff_id});await loadRoster()}
async function handleLock(ep){await fetch("/api/schedule",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"assign",staff_id:ep.staff_id,date:ep.shift_date||"",shift_code:ep.shift_code||"1423",unit:ep.unit,locked:!ep.locked})});await loadRoster()}
async function handleStaffSave(){var uu=staffForm.can_work_units?staffForm.can_work_units.split(",").map(function(s){return s.trim()}).filter(Boolean):[staffForm.home_unit];var body={name:staffForm.name,role:staffForm.role,home_unit:staffForm.home_unit,can_work_units:uu};if(editStaffId)await fetch("/api/schedule",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"staff_update",id:editStaffId,...body})});else await fetch("/api/schedule",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"staff_add",...body})});setShowStaffForm(false);setEditStaffId(null);setStaffForm({name:"",role:"RW",home_unit:"A",can_work_units:""});await loadAll()}
async function handleStaffDelete(id,name){if(!confirm("Delete "+name+"?"))return;await fetch("/api/schedule",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"staff_delete",id})});await loadAll();await loadRoster()}
async function handleLeaveSave(){await fetch("/api/schedule",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"leave_save",id:editLeaveId,...leaveForm})});setShowLeaveForm(false);setEditLeaveId(null);setLeaveForm({staff_id:0,start_date:"",end_date:"",leave_type:"annual"});await loadAll()}
async function handleLeaveDelete(id){if(!confirm("Delete leave?"))return;await fetch("/api/schedule",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"leave_delete",id})});await loadAll()}
if(loading)return <div className="flex items-center justify-center min-h-screen"><Loader2 size={32} className="animate-spin text-indigo-400"/></div>;
var monthLabel=new Date(currentMonth+"-01").toLocaleDateString("zh-TW",{year:"numeric",month:"long"});
return <div className="p-4 max-w-full">
<style>{"/*FC*/ .fc{background:transparent!important;color:#a1a1aa!important}.fc-toolbar-title{font-size:0}.fc-header-toolbar{display:none}.fc-col-header-cell{background:#27272a;border-color:#3f3f46;padding:3px 0;font-size:10px}.fc-daygrid-day{background:#18181b;border-color:#27272a}.fc-day-today{background:#1e1b4b!important}.fc-daygrid-day-number{color:#71717a;font-size:10px;padding:2px 4px}.fc-daygrid-event{border-radius:4px;margin:1px 2px;padding:1px 3px;font-size:9px;border:none;cursor:pointer}.fc-daygrid-event:hover{filter:brightness(1.2)}.fc-daygrid-day-frame{min-height:40px}.fc-scrollgrid{border-color:#27272a!important}.fc-scrollgrid-section-header{border:none!important}"}</style>
<div className="flex items-center justify-between flex-wrap gap-3 mb-4"><div><h1 className="text-xl font-bold text-zinc-100">智能排更</h1><p className="text-xs text-zinc-500 mt-0.5">{activeStaff.length} staff · {activeUnits.length} units · {assignments.length} shifts</p></div><div className="flex items-center gap-2"><Button variant="secondary" size="sm" onClick={handleClear}><RotateCcw size={13} className="mr-1"/>清空</Button><Button variant="secondary" size="sm" onClick={handleCopyRoster}><Copy size={13} className="mr-1"/>複製</Button><Button variant="secondary" size="sm" onClick={handleExportCSV}><Download size={13} className="mr-1"/>匯出</Button><Button variant="secondary" size="sm" onClick={function(){setShowSettings(true);setSettingsTab("constraints")}}><Settings2 size={13} className="mr-1"/>設定</Button><Button variant="primary" size="sm" onClick={handleSolve} disabled={solving}>{solving?<Loader2 size={14} className="mr-1 animate-spin"/>:<Zap size={14} className="mr-1"/}{solving?"計算中":"自動排更"}</Button></div></div>
{msg?<div className="rounded-xl p-3 text-sm bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 mb-4">{msg}</div>:null}
{showSettings?<SettingsModal units={units} roles={roles} assignments={assignments} leaveList={leaveList} onClose={function(){setShowSettings(false)}} onReload={loadAll} tab={settingsTab} setTab={setSettingsTab}/>:null}
<div className="flex gap-4">
<div className="w-48 shrink-0 space-y-3">
<div className="bg-zinc-900/60 border border-zinc-800 rounded-xl"><div className="flex items-center justify-between px-3 pt-3 pb-2"><p className="text-[10px] font-semibold text-zinc-500 uppercase">職員</p><button onClick={function(){setEditStaffId(null);setStaffForm({name:"",role:roles[0]?.code||"RW",home_unit:activeUnits[0]?.code||"A",can_work_units:""});setShowStaffForm(true)}} className="text-indigo-400 hover:text-indigo-300"><UserPlus size={13}/></button></div><div className="px-2 pb-2 space-y-0.5 max-h-[220px] overflow-y-auto">{activeStaff.map(function(s){return <div key={s.id} className="flex items-center gap-1.5 p-1.5 rounded text-[11px] group hover:bg-zinc-800/50"><div className="w-5 h-5 rounded-full flex items-center justify-center text-[8px] font-bold text-white shrink-0" style={{backgroundColor:unitColor(s.home_unit)}}>{initials(s.name)}</div><span className="text-zinc-400 truncate flex-1">{s.name}</span><div className="hidden group-hover:flex gap-0.5"><button onClick={function(){setEditStaffId(s.id);setStaffForm({name:s.name,role:s.role,home_unit:s.home_unit,can_work_units:(s.can_work_units||[]).join(", ")});setShowStaffForm(true)}} className="p-0.5 hover:bg-zinc-700 rounded"><Edit3 size={9} className="text-zinc-400"/></button><button onClick={function(){handleStaffDelete(s.id,s.name)}} className="p-0.5 hover:bg-red-500/20 rounded"><Trash2 size={9} className="text-red-400"/></button></div></div>})}</div></div>
<div className="bg-zinc-900/60 border border-zinc-800 rounded-xl"><div className="flex items-center justify-between px-3 pt-3 pb-2"><p className="text-[10px] font-semibold text-zinc-500 uppercase">請假</p><button onClick={function(){setEditLeaveId(null);setLeaveForm({staff_id:activeStaff[0]?.id||0,start_date:currentMonth+"-01",end_date:currentMonth+"-01",leave_type:"annual"});setShowLeaveForm(true)}} className="text-amber-400 hover:text-amber-300"><CalendarPlus size={13}/></button></div><div className="px-2 pb-2 space-y-0.5 max-h-[150px] overflow-y-auto">{leaveList.filter(function(l){return l.end_date>=currentMonth+"-01"}).slice(0,6).map(function(l){return <div key={l.id} className="text-[10px] text-zinc-500 p-1.5 border-b border-zinc-800/50 flex items-center gap-1.5 group"><span className="w-1 h-1 rounded-full bg-amber-500 shrink-0"/><span className="text-zinc-300 truncate flex-1">{l.staff_name}</span><span className="text-zinc-600">{l.start_date}~{l.end_date}</span><button onClick={function(){handleLeaveDelete(l.id)}} className="hidden group-hover:block p-0.5 hover:bg-red-500/20 rounded"><Trash2 size={8} className="text-red-400"/></button></div>})}{leaveList.length===0?<p className="text-[10px] text-zinc-600 p-1.5">無請假</p>:null}</div></div>
<div className="bg-zinc-900/60 border border-zinc-800 rounded-xl"><div className="flex items-center justify-between px-3 pt-3 pb-2 cursor-pointer" onClick={function(){setShowStats(!showStats)}}><p className="text-[10px] font-semibold text-zinc-500 uppercase flex items-center gap-1"><BarChart3 size={11}/>工時</p><span className="text-[10px] text-zinc-600">{showStats?"▲":"▼"}</span></div>{showStats?<div className="px-2 pb-2 space-y-1 max-h-[200px] overflow-y-auto">{workload.slice(0,8).map(function(w){return <div key={w.name} className="flex items-center gap-1.5 text-[10px] py-0.5"><span className="w-12 truncate text-zinc-300">{w.name}</span><div className="flex-1 h-1 bg-zinc-800 rounded-full overflow-hidden"><div className="h-full rounded-full" style={{width:Math.min(100,w.count/31*100)+"%",backgroundColor:roleColor(w.role)}}/></div><span className="w-6 text-right text-zinc-500">{w.count}</span></div>})}</div>:null}</div>
</div>
<div className="flex-1 space-y-2">{activeUnits.map(function(unit){return <div key={unit.code} className="bg-zinc-900/60 border border-zinc-800 rounded-xl overflow-hidden"><div className="flex items-center gap-2 px-4 py-2 border-b border-zinc-800 bg-zinc-800/30"><div className="w-2.5 h-2.5 rounded-full" style={{backgroundColor:unit.color}}/><span className="text-xs font-semibold text-zinc-300">{unit.name}</span><span className="text-[10px] text-zinc-600 ml-auto">{(eventsByUnit[unit.code]||[]).length} shifts</span></div><div className="p-2"><FullCalendar plugins={[dayGridPlugin,interactionPlugin]} initialView="dayGridMonth" initialDate={currentMonth+"-01"} events={eventsByUnit[unit.code]||[]} height="auto" headerToolbar={{left:"",center:"",right:""}} datesSet={function(info){setCurrentMonth(info.start.toISOString().slice(0,7))}} dateClick={function(info){var s=activeStaff[0];if(s)handleAssign(s.id,info.dateStr,unit.code)}} eventClick={function(info){var ep=info.event.extendedProps;if(ep&&ep.id){if(confirm("Lock/Unlock this shift?"))handleLock(ep);else handleDeleteAss(ep)}}}/></div></div>})}</div>
</div>
{showStaffForm?<div className="fixed inset-0 bg-black/60 flex items-center justify-center z-50" onClick={function(){setShowStaffForm(false)}}><div className="bg-zinc-900 border border-zinc-700 rounded-2xl p-5 w-[380px]" onClick={function(e){e.stopPropagation()}}><div className="flex items-center justify-between mb-4"><p className="text-sm font-semibold text-zinc-100">{editStaffId?"編輯職員":"新增職員"}</p><button onClick={function(){setShowStaffForm(false)}}><X size={16} className="text-zinc-500"/></button></div>
<div className="space-y-3"><div><label className="text-[10px] text-zinc-500">姓名</label><input value={staffForm.name} onChange={function(e){setStaffForm({...staffForm,name:e.target.value})}} className="w-full bg-zinc-800 border border-zinc-700 rounded-xl px-3 py-2.5 text-sm mt-1 text-zinc-100" placeholder="陳主任"/></div>
<div className="flex gap-3"><div className="flex-1"><label className="text-[10px] text-zinc-500">角色</label><select value={staffForm.role} onChange={function(e){setStaffForm({...staffForm,role:e.target.value})}} className="w-full bg-zinc-800 border border-zinc-700 rounded-xl px-3 py-2.5 text-sm mt-1 text-zinc-100">{roles.map(function(r){return <option key={r.code} value={r.code}>{r.name}</option>})}</select></div>
<div className="flex-1"><label className="text-[10px] text-zinc-500">家社</label><select value={staffForm.home_unit} onChange={function(e){setStaffForm({...staffForm,home_unit:e.target.value})}} className="w-full bg-zinc-800 border border-zinc-700 rounded-xl px-3 py-2.5 text-sm mt-1 text-zinc-100">{activeUnits.map(function(u){return <option key={u.code} value={u.code}>{u.name}</option>})}</select></div>
</div>
<div><label className="text-[10px] text-zinc-500">可跨社 (逗號分隔)</label><input value={staffForm.can_work_units} onChange={function(e){setStaffForm({...staffForm,can_work_units:e.target.value})}} className="w-full bg-zinc-800 border border-zinc-700 rounded-xl px-3 py-2.5 text-sm mt-1 text-zinc-100" placeholder={staffForm.home_unit}/></div>
</div>
<div className="flex gap-2 mt-5"><Button variant="secondary" size="sm" className="flex-1" onClick={function(){setShowStaffForm(false)}}>取消</Button><Button variant="primary" size="sm" className="flex-1" onClick={handleStaffSave} disabled={!staffForm.name.trim()}>{editStaffId?"儲存":"新增"}</Button></div>
</div>
</div>
:null}
{showLeaveForm?<div className="fixed inset-0 bg-black/60 flex items-center justify-center z-50" onClick={function(){setShowLeaveForm(false)}}><div className="bg-zinc-900 border border-zinc-700 rounded-2xl p-5 w-[380px]" onClick={function(e){e.stopPropagation()}}><div className="flex items-center justify-between mb-4"><p className="text-sm font-semibold text-zinc-100">{editLeaveId?"編輯請假":"新增請假"}</p><button onClick={function(){setShowLeaveForm(false)}}><X size={16} className="text-zinc-500"/></button></div>
<div className="space-y-3"><div><label className="text-[10px] text-zinc-500">職員</label><select value={leaveForm.staff_id} onChange={function(e){setLeaveForm({...leaveForm,staff_id:Number(e.target.value)})}} className="w-full bg-zinc-800 border border-zinc-700 rounded-xl px-3 py-2.5 text-sm mt-1 text-zinc-100">{activeStaff.map(function(s){return <option key={s.id} value={s.id}>{s.name}</option>})}</select></div>
<div className="flex gap-3"><div className="flex-1"><label className="text-[10px] text-zinc-500">開始</label><input type="date" value={leaveForm.start_date} onChange={function(e){setLeaveForm({...leaveForm,start_date:e.target.value})}} className="w-full bg-zinc-800 border border-zinc-700 rounded-xl px-3 py-2.5 text-sm mt-1 text-zinc-100"/></div>
<div className="flex-1"><label className="text-[10px] text-zinc-500">結束</label><input type="date" value={leaveForm.end_date} onChange={function(e){setLeaveForm({...leaveForm,end_date:e.target.value})}} className="w-full bg-zinc-800 border border-zinc-700 rounded-xl px-3 py-2.5 text-sm mt-1 text-zinc-100"/></div>
</div>
<div><label className="text-[10px] text-zinc-500">類型</label><select value={leaveForm.leave_type} onChange={function(e){setLeaveForm({...leaveForm,leave_type:e.target.value})}} className="w-full bg-zinc-800 border border-zinc-700 rounded-xl px-3 py-2.5 text-sm mt-1 text-zinc-100"><option value="annual">年假</option><option value="sick">病假</option><option value="time_off">補假</option><option value="training">培訓</option><option value="other">其他</option></select></div>
</div>
<div className="flex gap-2 mt-5"><Button variant="secondary" size="sm" className="flex-1" onClick={function(){setShowLeaveForm(false)}}>取消</Button><Button variant="primary" size="sm" className="flex-1" onClick={handleLeaveSave} disabled={!leaveForm.staff_id||!leaveForm.start_date}>{editLeaveId?"儲存":"新增"}</Button></div>
</div>
</div>
:null}
{showReplace?<div className="fixed inset-0 bg-black/60 flex items-center justify-center z-50" onClick={function(){setShowReplace(null)}}><div className="bg-zinc-900 border border-zinc-700 rounded-2xl p-5 w-[420px]" onClick={function(e){e.stopPropagation()}}><div className="flex items-center justify-between mb-4"><p className="text-sm font-semibold text-zinc-100">替代建議</p><button onClick={function(){setShowReplace(null)}}><X size={16} className="text-zinc-500"/></button></div><p className="text-xs text-zinc-500 mb-3">已移除 {showReplace.removing}，推薦替代：</p><div className="space-y-2 max-h-[250px] overflow-y-auto">{getSuggestions(showReplace.date,showReplace.unit,showReplace.staffId||0).map(function(s){return <button key={s.id} onClick={function(){handleAssign(s.id,showReplace.date,showReplace.unit)}} className="w-full text-left p-3 rounded-xl bg-zinc-800/50 hover:bg-zinc-700/50 flex items-center gap-3 group"><div className="w-7 h-7 rounded-full flex items-center justify-center text-[10px] font-bold text-white" style={{backgroundColor:unitColor(s.home_unit)}}>{initials(s.name)}</div><div><p className="text-sm text-zinc-200">{s.name} <span className="text-[10px] text-zinc-500">{s.role}</span></p></div><span className="text-[10px] text-indigo-400 opacity-0 group-hover:opacity-100 ml-auto">選擇 →</span></button>})}{getSuggestions(showReplace.date,showReplace.unit,showReplace.staffId||0).length===0?<p className="text-xs text-zinc-600 text-center py-4">暫無合適替代人選</p>:null}</div></div></div>:null}
</div>);
}
function SettingsModal(props){var units=props.units||[];var roles=props.roles||[];var onClose=props.onClose;var onReload=props.onReload;var tab=props.tab||"constraints";var setTab=props.setTab||function(){};
var[n,setN]=useState("");var[c,setC]=useState("");var[cl,setCl]=useState("#818cf8");
var colors=["#818cf8","#22c55e","#f59e0b","#ef4444","#06b6d4","#ec4899","#a855f7","#f43f5e"];
async function saveUnit(id,name,code,color){await fetch("/api/schedule",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"unit_save",id:id||null,name:name,code:code,color:color||"#22c55e"})});if(onReload)onReload()}
async function delUnit(id){if(!confirm("Delete?"))return;await fetch("/api/schedule",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"unit_delete",id})});if(onReload)onReload()}
async function saveRole(id,name,code,color){await fetch("/api/schedule",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"role_save",id:id||null,name:name,code:code,color:color})});if(onReload)onReload()}
async function delRole(id){if(!confirm("Delete?"))return;await fetch("/api/schedule",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"role_delete",id})});if(onReload)onReload()}
var[localConfig,setLocalConfig]=useState(null);var[saving,setSaving]=useState(false);var[saved,setSaved]=useState(false);
useEffect(function(){fetch("/api/schedule?sub=config").then(function(r){return r.json()}).then(function(d){if(d&&d.config_json)setLocalConfig(d.config_json)})},[]);
function updateHard(k,f,v){var hc={...localConfig.hard_constraints};hc[k]={...(hc[k]||{})};hc[k][f]=v;setLocalConfig({...localConfig,hard_constraints:hc})}
function updateSoft(k,f,v){var sc={...localConfig.soft_constraints};sc[k]={...(sc[k]||{})};sc[k][f]=v;setLocalConfig({...localConfig,soft_constraints:sc})}
async function saveConfig(){setSaving(true);await fetch("/api/schedule",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"config_save",config_json:localConfig})});setSaving(false);setSaved(true);if(onReload)onReload();setTimeout(function(){setSaved(false)},2000)}
return <div className="fixed inset-0 bg-black/60 flex items-center justify-center z-50" onClick={onClose}><div className="bg-zinc-900 border border-zinc-700 rounded-2xl p-6 w-[560px] max-h-[85vh] overflow-y-auto shadow-2xl" onClick={function(e){e.stopPropagation()}}><div className="flex items-center justify-between mb-4"><p className="text-sm font-semibold text-zinc-100 flex items-center gap-2"><Settings2 size={14} className="text-indigo-400"/>設定</p><button onClick={onClose}><X size={16} className="text-zinc-500"/></button></div>
<div className="flex gap-1 mb-4 bg-zinc-800 rounded-lg p-0.5"><button onClick={function(){setTab("constraints")}} className={"flex-1 py-1.5 rounded-md text-xs font-medium "+(tab==="constraints"?"bg-zinc-700 text-white":"text-zinc-500 hover:text-zinc-300")}>約束</button><button onClick={function(){setTab("units")}} className={"flex-1 py-1.5 rounded-md text-xs font-medium "+(tab==="units"?"bg-zinc-700 text-white":"text-zinc-500 hover:text-zinc-300")}>家社</button><button onClick={function(){setTab("roles")}} className={"flex-1 py-1.5 rounded-md text-xs font-medium "+(tab==="roles"?"bg-zinc-700 text-white":"text-zinc-500 hover:text-zinc-300")}>角色</button></div>
{tab==="constraints"&&localConfig?<div><p className="text-[11px] font-semibold text-zinc-400 mb-2 uppercase tracking-wide">HARD</p><div className="space-y-3 mb-4"><HardRow label="夜更後休息" desc="做夜更後最少休息時數" unit="小時" min={0} max={72} step={1} enabled={localConfig.hard_constraints.night_rest_24h?localConfig.hard_constraints.night_rest_24h.enabled!==false:false} value={localConfig.hard_constraints.night_rest_24h?localConfig.hard_constraints.night_rest_24h.hours||24:24} onToggle={function(){updateHard("night_rest_24h","enabled",!((localConfig.hard_constraints.night_rest_24h||{}).enabled!==false))}} onChange={function(v){updateHard("night_rest_24h","hours",v)}}/><HardRow label="連續工作上限" desc="每人最多連續工作天數" unit="日" min={0} max={14} step={1} enabled={localConfig.hard_constraints.max_consecutive_days?localConfig.hard_constraints.max_consecutive_days.enabled!==false:false} value={localConfig.hard_constraints.max_consecutive_days?localConfig.hard_constraints.max_consecutive_days.value||6:6} onToggle={function(){updateHard("max_consecutive_days","enabled",!((localConfig.hard_constraints.max_consecutive_days||{}).enabled!==false))}} onChange={function(v){updateHard("max_consecutive_days","value",v)}}/></div>
<p className="text-[11px] font-semibold text-zinc-400 mb-2 uppercase tracking-wide">SOFT</p><div className="space-y-3 mb-4">{[{k:"avoid_consecutive_nights",l:"避免連續夜更"},{k:"fair_weekend_distribution",l:"公平分配週末"},{k:"as_avoid_night",l:"主管避免夜更"},{k:"minimize_cross_unit",l:"減少跨社調動"},{k:"same_unit_continuity",l:"同社連續工作"},{k:"abc_group_constraint",l:"ABC組約束"}].map(function(item){var cfg=localConfig.soft_constraints[item.k]||{};return <SoftRow key={item.k} label={item.l} weight={cfg.weight||0} enabled={cfg.enabled!==false} onToggle={function(){updateSoft(item.k,"enabled",!((localConfig.soft_constraints[item.k]||{}).enabled!==false))}} onChange={function(v){updateSoft(item.k,"weight",v)}}/>})}</div>
<div className="bg-indigo-500/10 border border-indigo-500/20 rounded-xl p-3 mb-4"><p className="text-[10px] text-indigo-400 flex items-center gap-1"><Info size={12}/>所有數值可自行調整。修改後按「自動排更」生效。</p></div>
<div className="flex gap-2"><Button variant="secondary" size="sm" className="flex-1" onClick={onClose}>關閉</Button><Button variant="primary" size="sm" className="flex-1" onClick={saveConfig} disabled={saving}>{saved?"已儲存":"儲存設定"}</Button></div>
</div>
:tab==="constraints"?<div className="text-center py-8"><Loader2 size={24} className="animate-spin text-indigo-400 mx-auto"/></div>
:null}
{tab==="units"?<div className="space-y-2">{units.map(function(u){return <div key={u.id} className="flex items-center gap-3 p-2.5 rounded-xl bg-zinc-800/30 group"><div className="w-3 h-3 rounded-full shrink-0" style={{backgroundColor:u.color}}/><div className="flex-1"><p className="text-xs text-zinc-200">{u.name}</p><p className="text-[10px] text-zinc-600">{u.code}</p></div><div className="hidden group-hover:flex gap-1"><button onClick={function(){var nn=prompt("名稱",u.name);if(nn)saveUnit(u.id,nn,u.code,u.color)}} className="p-1 hover:bg-zinc-700 rounded"><Edit3 size={10} className="text-zinc-400"/></button><button onClick={function(){delUnit(u.id)}} className="p-1 hover:bg-red-500/20 rounded"><Trash2 size={10} className="text-red-400"/></button></div></div>})}<div className="flex gap-2 pt-2 border-t border-zinc-800"><input value={n} onChange={function(e){setN(e.target.value)}} placeholder="名稱" className="flex-1 bg-zinc-800 border-zinc-700 rounded-lg px-2.5 py-1.5 text-xs text-zinc-200"/><input value={c} onChange={function(e){setC(e.target.value)}} placeholder="代碼" className="w-16 bg-zinc-800 border-zinc-700 rounded-lg px-2.5 py-1.5 text-xs text-zinc-200"/><Button variant="primary" size="sm" className="text-[10px]" onClick={function(){if(n&&c){saveUnit(null,n,c,"#22c55e");setN("");setC("")}}} disabled={!n||!c}><Plus size={12}/></Button></div></div>:null}
{tab==="roles"?<div className="space-y-2">{roles.map(function(r){return <div key={r.id} className="flex items-center gap-3 p-2.5 rounded-xl bg-zinc-800/30 group"><div className="w-3 h-3 rounded-full shrink-0" style={{backgroundColor:r.color}}/><div className="flex-1"><p className="text-xs text-zinc-200">{r.name}</p><p className="text-[10px] text-zinc-600">{r.code}</p></div><div className="hidden group-hover:flex gap-1"><button onClick={function(){var nn=prompt("名稱",r.name);if(nn)saveRole(r.id,nn,r.code,r.color)}} className="p-1 hover:bg-zinc-700 rounded"><Edit3 size={10} className="text-zinc-400"/></button><button onClick={function(){delRole(r.id)}} className="p-1 hover:bg-red-500/20 rounded"><Trash2 size={10} className="text-red-400"/></button></div></div>})}<div className="flex gap-2 pt-2 border-t border-zinc-800"><input value={n} onChange={function(e){setN(e.target.value)}} placeholder="名稱" className="flex-1 bg-zinc-800 border-zinc-700 rounded-lg px-2.5 py-1.5 text-xs text-zinc-200"/><input value={c} onChange={function(e){setC(e.target.value)}} placeholder="代碼" className="w-16 bg-zinc-800 border-zinc-700 rounded-lg px-2.5 py-1.5 text-xs text-zinc-200"/><div className="flex gap-1 items-center">{colors.map(function(co){return <button key={co} onClick={function(){setCl(co)}} className={"w-3.5 h-3.5 rounded-full border-2 "+(cl===co?"border-white":"border-transparent")} style={{backgroundColor:co}}/>})}</div><Button variant="primary" size="sm" className="text-[10px]" onClick={function(){if(n&&c){saveRole(null,n,c,cl);setN("");setC("")}}} disabled={!n||!c}><Plus size={12}/></Button></div></div>:null}
</div></div>}

function HardRow(p){return <div className="p-3 rounded-xl bg-zinc-800/30"><div className="flex items-center justify-between mb-2"><div><p className="text-xs font-medium text-zinc-200">{p.label}</p><p className="text-[10px] text-zinc-500 mt-0.5">{p.desc}</p></div><div className={"w-10 h-5 rounded-full transition-colors cursor-pointer shrink-0 "+(p.enabled?"bg-indigo-500":"bg-zinc-600")} onClick={p.onToggle}><div className={"w-4 h-4 rounded-full bg-white mt-0.5 transition-transform "+(p.enabled?"translate-x-5":"translate-x-0.5")}/></div></div>{p.enabled?<div className="flex items-center gap-2"><input type="number" min={p.min} max={p.max} step={p.step} value={p.value} onChange={function(e){p.onChange(parseInt(e.target.value)||0)}} className="w-16 bg-zinc-700 border border-zinc-600 rounded-lg px-2 py-1 text-xs text-zinc-200 text-center"/><span className="text-[10px] text-zinc-500">{p.unit}</span></div>:null}</div>}
function SoftRow(p){return <div className="p-3 rounded-xl bg-zinc-800/30"><div className="flex items-center justify-between mb-2"><p className="text-xs font-medium text-zinc-200">{p.label}</p><div className={"w-10 h-5 rounded-full transition-colors cursor-pointer shrink-0 "+(p.enabled?"bg-indigo-500":"bg-zinc-600")} onClick={p.onToggle}><div className={"w-4 h-4 rounded-full bg-white mt-0.5 transition-transform "+(p.enabled?"translate-x-5":"translate-x-0.5")}/></div></div>{p.enabled?<div className="flex items-center gap-3"><span className="text-[10px] text-zinc-500 w-8">權重</span><input type="range" min={0} max={500} step={10} value={p.weight} onChange={function(e){p.onChange(parseInt(e.target.value))}} className="flex-1 h-1 accent-indigo-500"/><span className="text-xs text-indigo-400 font-mono w-8 text-right">{p.weight}</span></div>:null}</div>}